name: Build Executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller flet
      - name: Build EXE
      # Странно, но на винде это работает (
        run: pyinstaller --onefile --noconsole --hidden-import=flet --collect-all flet --name flet_app lesson_2.py
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/flet_app.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller flet
      - name: Build MacOS executable
        run: pyinstaller --onefile --noconsole --hidden-import=flet --collect-all flet --target-architecture universal2 --name flet_app lesson_2.py
      - name: Set executable permissions
        run: chmod +x dist/flet_app
      - name: Upload MacOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: dist/flet_app
